server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: sxh.200008
  
  redis:
    host: 127.0.0.1
    # password: foobared
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8

  mqtt:
    username: admin #账户
    password: sxh.200008 # 密码
    hostUrl: tcp://localhost:1883 # MQTT-服务器连接地址
    clientId: skwl_mqtt_client # MQTT-连接服务器默认客户端ID, 每个客户端启动的id要不同
    receiveTopics: abc_topic,$share/g1/test # 监听的消息队列 $share/g1/test是使用g1组订阅test消息队列，同组间不会重复消费
    timeout: 10 # 超时时间 单位/s
    keepAlive: 20 # 心跳的间隔


#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    header: Authorization
    expire: 29030400 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

